### ISSUE TITLE
"sea_floor_depth_below_X" is not a vertical coordinate

### ISSUE THREAD

**Issue by mhidas** [aodn/cc-plugin-imos#25]
The util function `vertical_coordinate_type()` correctly exempts variables with standard_name "sea_floor_depth_below_sea_surface" from being regarded as a vertical coordinate. However, there are several other variants on this standard_name (e.g. "sea_floor_depth_below_mean_sea_level"), which should equally be exempt. The exemption (line [107](https://github.com/aodn/cc-plugin-imos/blob/master/cc_plugin_imos/util.py#L107)) should be broadened to any standard name starting with "sea_floor_depth" (including this exact string).

**Comment by bpasquer** [comment]
This issue was open last June after I run the checker on the Satellite SAR Wave NetCDF files. There is always the option of disabling the relevant checks in the pipeline while waiting for the fix and I guess @mhidas hasn't got much time to fix it, but maybe another PO could do it,  now that we are getting ready to publish these data. 
 @ggalibert ?

**Comment by mhidas** [comment]
Here's a quick fix: #40
Might just do the trick. Just waiting to see if the unittests pass....

**Comment by mhidas** [comment]
Sorry, this change can't be deployed until https://github.com/aodn/issues/issues/583 is resolved.

**Comment by bpasquer** [comment]
Thanks @mhidas . At least we are a step closer to resolving this issue
